### ISSUE TITLE
Please publish to Rubygems

### ISSUE THREAD

**Issue by dankohn** [ataber/rubill#11]
Could you please rev the version number and publish to Rubygems? If you'd like help, you could make @dmitry-ilyashevich a committer and he could do it for you. Thanks!

**Comment by ataber** [comment]
Will do! ETA: by the end of the week

**Comment by dankohn** [comment]
Thanks!

--
Dan Kohn <mailto:dan@dankohn.com>
tel:+1-415-233-1000

**Comment by ataber** [comment]
Okay, [here it is!](https://rubygems.org/gems/rubill)

**Comment by dmitry-ilyashevich** [comment]
@ataber 1.0.2 is broken. You have in rubill.rb:

````
require "rubill/bill_payment"
...
require "rubill/sent_bill_payment"
````

But not corresponding files from the same commit...

https://github.com/ataber/rubill/commit/7a6b55804b3e4463c204c964ce1507429ec83571

**Comment by dankohn** [comment]
Also, please tag gem version number as a release tag.

https://help.github.com/articles/about-releases/
https://help.github.com/articles/creating-releases/

**Comment by ataber** [comment]
Whoops! Thanks for pointing that out. I'll get on that tonight

**Comment by ataber** [comment]
Give it a try now, I think it should work!

**Comment by dmitry-ilyashevich** [comment]
Nope :disappointed: 

There is no 'rubill/attachment' module in 0.1.5

**Comment by ataber** [comment]
Okay I fixed that issue. Give it another try. Thanks for your patience!

**Comment by dmitry-ilyashevich** [comment]
:+1:
